# Generated by scripts/gen-packaging.mjs — do not edit by hand.
# Tap install:
#   brew tap click6067-ship-it/fitllm https://github.com/click6067-ship-it/fitllm-engine
#   brew install fitllm
#
# This is a binary formula. homebrew-core does not accept prebuilt binaries and
# its notability bar for self-submitted projects is 225 stars / 90 forks /
# 90 watchers, which this project does not meet — so a tap is the honest home
# for it today, not a workaround we are hiding.
class Fitllm < Formula
  desc "Will this LLM fit on your GPU or Mac? Architecture-accurate memory estimates"
  homepage "https://fitllm.run"
  version "2.18.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/click6067-ship-it/fitllm-engine/releases/download/v2.18.0/fitllm-v2.18.0-darwin-arm64"
      sha256 "c1eb98526fc2b1bd79076f64c424b465425650607d32d1b9c4d7ee6844250f7a"
    end
    on_intel do
      url "https://github.com/click6067-ship-it/fitllm-engine/releases/download/v2.18.0/fitllm-v2.18.0-darwin-x64"
      sha256 "31c01100e3236ba31788d5872299af4b901dd655e85002a14c6386c0dd918699"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/click6067-ship-it/fitllm-engine/releases/download/v2.18.0/fitllm-v2.18.0-linux-arm64"
      sha256 "9132a8aa0e6c07d7660efaf540cc1865d32437f2dd9a081711ea5d775a62d5da"
    end
    on_intel do
      url "https://github.com/click6067-ship-it/fitllm-engine/releases/download/v2.18.0/fitllm-v2.18.0-linux-x64"
      sha256 "1b16a76b25cb5b26e4fdb460ef9f7618052f8e72e0ae6a60fd206a1a577e86da"
    end
  end

  def install
    bin.install Dir["*"].first => "fitllm"
  end

  test do
    assert_match "FITS", shell_output("#{bin}/fitllm 'Gemma 4 31b' --gpu 'RTX 5090'")
  end
end
