# Generated by scripts/gen-packaging.mjs — do not edit by hand.
# Tap install:
#   brew tap click6067-ship-it/fitllm https://github.com/click6067-ship-it/fitllm-engine
#   brew install fitllm
#
# This is a binary formula. homebrew-core does not accept prebuilt binaries and
# its notability bar for self-submitted projects is 225 stars / 90 forks /
# 90 watchers, which this project does not meet — so a tap is the honest home
# for it today, not a workaround we are hiding.
class Fitllm < Formula
  desc "Will this LLM fit on your GPU or Mac? Architecture-accurate memory estimates"
  homepage "https://fitllm.run"
  version "2.16.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/click6067-ship-it/fitllm-engine/releases/download/v2.16.0/fitllm-v2.16.0-darwin-arm64"
      sha256 "6d5a7b47ad1f9d3b08f0b21d36b932c683c92597191cd9de8dbf208536ea6196"
    end
    on_intel do
      url "https://github.com/click6067-ship-it/fitllm-engine/releases/download/v2.16.0/fitllm-v2.16.0-darwin-x64"
      sha256 "040f948391485d05bf794a108d05158fa2bc3993058b47678e1580f4587e89cf"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/click6067-ship-it/fitllm-engine/releases/download/v2.16.0/fitllm-v2.16.0-linux-arm64"
      sha256 "e3f3c56378b09d637e2defcf7f1ef6c644a64bef034b775118b23cc90a5d9461"
    end
    on_intel do
      url "https://github.com/click6067-ship-it/fitllm-engine/releases/download/v2.16.0/fitllm-v2.16.0-linux-x64"
      sha256 "2f2e76f61ceb3a8dbb2f966e8e9590a565466f22b10f75312d7459dff52551d0"
    end
  end

  def install
    bin.install Dir["*"].first => "fitllm"
  end

  test do
    assert_match "FITS", shell_output("#{bin}/fitllm 'Gemma 4 31b' --gpu 'RTX 5090'")
  end
end
