# Generated by scripts/gen-packaging.mjs — do not edit by hand.
# Tap install:
#   brew tap click6067-ship-it/fitllm https://github.com/click6067-ship-it/fitllm-engine
#   brew install fitllm
#
# This is a binary formula. homebrew-core does not accept prebuilt binaries and
# its notability bar for self-submitted projects is 225 stars / 90 forks /
# 90 watchers, which this project does not meet — so a tap is the honest home
# for it today, not a workaround we are hiding.
class Fitllm < Formula
  desc "Will this LLM fit on your GPU or Mac? Architecture-accurate memory estimates"
  homepage "https://fitllm.run"
  version "2.17.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/click6067-ship-it/fitllm-engine/releases/download/v2.17.0/fitllm-v2.17.0-darwin-arm64"
      sha256 "5dafa50b89367fd984840cb5d42937a9c2ef5c299703772ae8080de1e771f198"
    end
    on_intel do
      url "https://github.com/click6067-ship-it/fitllm-engine/releases/download/v2.17.0/fitllm-v2.17.0-darwin-x64"
      sha256 "c426f0865a9f28dc26b6230e1e33415a1d8d456a553bbc5db3b2d91dcacbca70"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/click6067-ship-it/fitllm-engine/releases/download/v2.17.0/fitllm-v2.17.0-linux-arm64"
      sha256 "c4921e4c2ff20c0156c8eab539704abbfe3369fcf3b1fdfc04ecfbb6587f7004"
    end
    on_intel do
      url "https://github.com/click6067-ship-it/fitllm-engine/releases/download/v2.17.0/fitllm-v2.17.0-linux-x64"
      sha256 "a763380bc99254b56b2f7a9b9f4319767890adff0af72e7c2fc57c31ce0571a6"
    end
  end

  def install
    bin.install Dir["*"].first => "fitllm"
  end

  test do
    assert_match "FITS", shell_output("#{bin}/fitllm 'Gemma 4 31b' --gpu 'RTX 5090'")
  end
end
